### ISSUE TITLE
Google Assistant Integration

### ISSUE THREAD

**Issue by michaelfitzhavey** [holistic-web/home-orchestrator#12]
It seems like a good idea to add an app to allow us to set our themes through google assistant.

## Todo:
- [ ] begin investigation into how we would do this. This link seems like a good place to start: https://codelabs.developers.google.com/codelabs/actions-1/index.html?index=..%2F..index#2
- [ ] discuss and document implementation plan

**Comment by dan47bennett** [comment]
The codelab tutorials have been explored and they give information on using Google Assistant to perform "Actions", as described below. 

For a given conversation the following takes place:
- Action Invocation - user tells the Assistant that they want to connect to the home orchestrator. It seems that all possibile interactions with the HO would fall under one "Action".
- Welcome intent - what greeting/question the Assistant says to the user after the invocation.
- Slot-filling - after the user responds, the required parameters or instructions are parsed from the response using Dialogflow e.g. "lights off".
- Conversation - the Assistant will begin a conversation, asking questions until all necessary information is extracted
- Fulfillment - the creation of a usable webhook containing the information that has been extracted.

What needs to be exist for a complete action where we can have a user talk to the Assistant and the necessary information extracted:
- [x] Action project - where multiple actions can be stored.
- [ ] Dialogflow agent - this tool allows us to extract information from what a user has said.
- [ ] Welcome intent - first response from the Assistant.
- [ ] Dialogflow intent - what information we want the user to tell the HO e.g. which light to change
- [ ] Dialogflow webhook - a web request containing the information given.

**Comment by michaelfitzhavey** [comment]
@dan47bennett I believe the welcome intent can be avoided by using something called deep linking. This is where the initial invocation of our app (i.e. "Jarvis turn on the lights") both triggers the app (with the `Jarvis` keyword, and delivers an instruction (with the `turn on the lights`) keyword.

Also where can we see the Action Project? Is it under the home orchestrator project or can you share it with me? (michael.fitzhavey@gmail.com)
