### ISSUE TITLE
Minimum Milestone!

### ISSUE THREAD

**Issue by michaelfitzhavey** [holistic-web/home-orchestrator#6]
The project has been refactored to be readable and manageable now, however there are still some features left to implement.

## Themes
We need to allow the user to store the current state of lights as a theme to be applied later. 

_PR #8_
- [x] create a collection 'themes'
- [x] create a container displaying all themes
- [x] from lights page, allow user to save as a new theme
- [x] allow user to apply themes
- [x] allow user to delete and edit themes

## Buttons Section
We need to allow the user to configure what the buttons do from the orchestrator-ui. They will need to:
- [ ] create a collection 'buttons'
- [ ] create a container displaying all buttons
- [ ] display all buttons
- [ ] allow user to set a theme for the buttons to apply

## Light Types
There should be a collection of all known light types that allows us to store metadata about these lights, such as 'available scenes', 'scenes supported', etc.
- [ ] populate scenes from a collection of information about device types

## Plugs
3rd party plugs should also be able to be activated by this system

**Comment by michaelfitzhavey** [comment]
#8 has been created to add the concepts of Themes into the home orchestrator

**Comment by michaelfitzhavey** [comment]
Merging & Deploying #6

Remaining Todo: 
- [ ] add confirm modal to theme deletion
- [ ] add button to Lights page to save to theme (allow save to new theme)
- [ ] user can apply theme
- [ ] go over theme

**Comment by michaelfitzhavey** [comment]
#9 has been merging resolving most of these issues with the exception of: 
> add button to Lights page to save to theme (allow save to new theme)

**Comment by michaelfitzhavey** [comment]
#10 has been merged allowing:
- access to the database to be controlled by cloud functions
- user to control which emails can manage their home
- documentation tidied

**Comment by michaelfitzhavey** [comment]
I believe the bulk of this has been covered with the exception of buttons. The focus and direction of this project has adjusted as work has progressed and so once we create a new issue for handling button presses I think we can close this 😄

**Comment by michaelfitzhavey** [comment]
#27 has been created as an issue to track the progress of adding buttons. Closing this now!
